import Link from "next/link";
import { notFound } from "next/navigation";
import { getReport } from "@/lib/osint";
import { pageMetadata, siteUrl } from "@/lib/seo";
export const dynamic = "force-dynamic";
type Props = { params: Promise<{id: string}> };
export async function generateMetadata({params}: Props) { const {id} = await params; const report = await getReport(id); return report ? pageMetadata(report.title, "IMDO open-source intelligence. Dated developments, original sources, and practical implications.", `/osint/${id}`) : { title: "Report not found", robots: {index: false} }; }
const date = (timestamp: string) => new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", dateStyle: "long", timeStyle: "short" }).format(new Date(timestamp));
export default async function ReportPage({params}: Props) {
  const {id} = await params; const report = await getReport(id); if (!report) notFound();
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: report.title, datePublished: report.publishedAt, dateModified: report.updatedAt || report.publishedAt, author: {"@type": "Organization", name: "The Immanent Domain"}, mainEntityOfPage: `${siteUrl}/osint/${id}/` };
  return <main className="editorial-page osint-report"><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(schema).replace(/</g, "\\u003c")}}/><header><p className="kicker"><Link href="/osint">OSINT ↗</Link> / {report.series === "research" ? "Machine Intuition Research" : "Daily intelligence"}</p><h1>{report.title}</h1><p>Edition: {date(report.scheduledAt)} · New York</p><p>Published: <time dateTime={report.publishedAt}>{date(report.publishedAt)}</time> · New York</p>{report.updatedAt && <p>Updated: <time dateTime={report.updatedAt}>{date(report.updatedAt)}</time> · {report.correction}</p>}</header>
    <div className="osint-reading-layout"><nav className="osint-contents" aria-label="Report contents"><p className="kicker">In this edition</p>{report.sections.map((section, index) => <a key={section.title} href={`#field-${index + 1}`}><span>{String(index + 1).padStart(2, "0")}</span>{section.title}</a>)}</nav><div className="osint-report-body">{report.sections.map((section, index) => <section key={section.title} id={`field-${index + 1}`} className="osint-report-section"><p className="kicker">{String(index + 1).padStart(2, "0")} / Intelligence field</p><h2>{section.title}</h2>{section.shortfall && <p className="small-note">{section.shortfall}</p>}<ol>{section.entries.map(entry => <li key={entry.sourceUrl}><h3><a href={entry.sourceUrl} rel="noopener noreferrer">{entry.title} ↗</a></h3><p className="small-note">Source date: {entry.sourceDate}{entry.eventDate && ` · Event: ${entry.eventDate}`}</p><p>{entry.development}</p><p><strong>Why it matters:</strong> {entry.significance}</p>{entry.implications && <p><strong>Implications:</strong> {entry.implications}</p>}{entry.uncertainty && <p><strong>Evidence / uncertainty:</strong> {entry.uncertainty}</p>}</li>)}</ol></section>)}
    {report.nextMoves.length > 0 && <section className="osint-next-moves"><p className="kicker">Looking ahead</p><h2>Watch Points / Next Moves</h2><ol>{report.nextMoves.map(move => <li key={move}>{move}</li>)}</ol></section>}</div></div><p className="osint-return"><Link className="text-link" href="/osint">Return to OSINT ↗</Link></p>
  </main>;
}
